# Faye
development:
  server: "http://localhost:4000/faye"
  adapter_javascript_url: "http://localhost:4000/faye/faye.js"
  auth_token: "jaksdfhkajsdfhaksdfhaskdjf"
  adapter: "Faye"
  async: true

# Pusher
# development:
#   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
#   app_id: "YOUR_PUSHER_APP_ID"
#   api_key: "YOUR_PUSHER_API_KEY"
#   auth_token: "YOUR_PUSHER_SECRET"
#   adapter: "Pusher"
#   async: true

# Disabled
# development:
#   adapter: false

test:
  server: "http://localhost:4000/faye"
  adapter_javascript_url: "http://localhost:4000/faye/faye.js"
  adapter: "Faye"
  auth_token: "secret"
  async: false

production:
  server: "https://kaopiz-faye-server.herokuapp.com/faye"
  adapter_javascript_url: "https://kaopiz-faye-server.herokuapp.com/faye/faye.js"
  adapter: "Faye"
  auth_token: <=% ENV["SYNC_AUTH_TOKEN"] %>
  async: true
