# Faye
development:
  server: "http://localhost:4000/faye"
  adapter_javascript_url: "http://localhost:4000/faye/faye.js"
  auth_token: "jaksdfhkajsdfhaksdfhaskdjf"
  adapter: "Faye"
  async: true

# Pusher
# development:
#   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
#   app_id: "YOUR_PUSHER_APP_ID"
#   api_key: "YOUR_PUSHER_API_KEY"
#   auth_token: "YOUR_PUSHER_SECRET"
#   adapter: "Pusher"
#   async: true

# Disabled
# development:
#   adapter: false

test:
  server: "http://localhost:4000/faye"
  adapter_javascript_url: "http://localhost:4000/faye/faye.js"
  adapter: "Faye"
  auth_token: "secret"
  async: false

production:
  server: "http://example.com/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "8f145c86dcb9df44f9841529872cc3c4f2de9d41cc33e7ab590e016b983fd571"
  async: true
